name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # macOS only: accept Xcode license
      - name: Accept Xcode license
        if: matrix.os == 'macos-latest'
        run: sudo xcodebuild -license accept

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build APK (Android)
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --debug

      # macOS only: install CocoaPods
      - name: Install CocoaPods
        if: matrix.os == 'macos-latest'
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Build iOS (macOS)
        if: matrix.os == 'macos-latest'
        run: flutter build ios --no-codesign --debug
